EXPERIMENT:
  NAME: "vgg13_MobileNetV2_da"
  TAG: "kd,vgg13,MobileNetV2"
  PROJECT: "latent_da_final"
  DA: True
DISTILLER:
  TYPE: "LDA"
  TEACHER: "vgg13"
  STUDENT: "MobileNetV2"
DA:
  PROB: 0.25
  LR: 0.1
  EPOCHS: 1