EXPERIMENT:
  NAME: "wrn_40_2_resnet8x4_da"
  TAG: "kd,wrn_40_2,resnet8x4"
  PROJECT: "latent_da_final"
  DA: True
DISTILLER:
  TYPE: "LDA"
  TEACHER: "wrn_40_2"
  STUDENT: "resnet8x4"
DA:
  PROB: 0.25
  LR: 0.1
  EPOCHS: 1