EXPERIMENT:
  NAME: "wrn_40_2_wrn_40_1_da"
  TAG: "kd,wrn_40_2,wrn_40_1"
  PROJECT: "latent_da_final"
  DA: True
DISTILLER:
  TYPE: "LDA"
  TEACHER: "wrn_40_2"
  STUDENT: "wrn_40_1"
DA:
  PROB: 0.25
  LR: 0.1
  EPOCHS: 1