EXPERIMENT:
  NAME: "wrn_40_2_MobileNetV2_da"
  TAG: "kd,wrn_40_2,MobileNetV2"
  PROJECT: "latent_da_final"
  DA: True
DISTILLER:
  TYPE: "LDA"
  TEACHER: "wrn_40_2"
  STUDENT: "MobileNetV2"
DA:
  PROB: 0.25
  LR: 0.1
  EPOCHS: 1