EXPERIMENT:
  NAME: "resnet56_resnet20_da"
  TAG: "kd,resnet56,resnet20"
  PROJECT: "latent_da_final"
  DA: True
DISTILLER:
  TYPE: "LDA"
  TEACHER: "resnet56"
  STUDENT: "resnet20"
DA:
  PROB: 0.25
  LR: 0.1
  EPOCHS: 1