EXPERIMENT:
  NAME: "resnet32x4_wrn_40_2_da"
  TAG: "kd,resnet32x4,wrn_40_2"
  PROJECT: "latent_da_final"
  DA: True
DISTILLER:
  TYPE: "LDA"
  TEACHER: "resnet32x4"
  STUDENT: "wrn_40_2"
DA:
  PROB: 0.25
  LR: 0.1
  EPOCHS: 1