EXPERIMENT:
  NAME: "vgg13_MobileNetV2_da_old_mse"
  TAG: "kd,vgg13,MobileNetV2"
  PROJECT: "da_final"
  DA: True
DISTILLER:
  TYPE: "DA_MSE"
  TEACHER: "vgg13"
  STUDENT: "MobileNetV2"
DA:
  LR: 0.00192
  EPOCHS: 1
  PROB: 0.268