EXPERIMENT:
  NAME: "wrn_40_2_MobileNetV2_da_old"
  TAG: "kd,wrn_40_2,MobileNetV2"
  PROJECT: "da_final"
  DA: True
DISTILLER:
  TYPE: "DA_OLD"
  TEACHER: "wrn_40_2"
  STUDENT: "MobileNetV2"
DA:
  LR: 0.00192
  EPOCHS: 1
  PROB: 0.268